// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();

  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);

    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  };
}

<main class="container">
  <h2>Dados do Livro</h2>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        name="titulo"
        class="form-control"
        required
        [(ngModel)]="livro.titulo"
      />
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        name="resumo"
        class="form-control"
        [(ngModel)]="livro.resumo"
      ></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select
        name="editora"
        class="form-control"
        required
        [(ngModel)]="livro.codEditora"
      >
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea
        name="autores"
        class="form-control"
        [(ngModel)]="autoresForm"
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import { Menu } from '@/componentes/Menu';
import { ControleEditora } from '@/models/controle/ControleEditora';
import { ControleLivros } from '@/models/controle/ControleLivros';
import { Livro } from '@/models/modelo/Livro';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';

const controleEditora: ControleEditora = new ControleEditora();
const controleLivros = new ControleLivros();

const LivroDados = () => {
  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState<number>(opcoes[0].value);
  const navigate = useRouter().push;

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro: Livro = {
      codigo: '',
      titulo: titulo,
      resumo: resumo,
      autores: autores.split('\n'),
      codEditora: codEditora,
    };
    controleLivros.incluir(livro).then(() => {
      navigate('/LivroLista');
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Dados do Livro</title>
      </Head>

      <Menu />

      <main className="container">
        <h1 className={styles.title}>Dados do Livro</h1>

        <form onSubmit={incluir}>
          <div className="form-group">
            <label htmlFor="titulo">Título</label>
            <input
              type="text"
              id="titulo"
              className="form-control"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label htmlFor="resumo">Resumo</label>
            <textarea
              id="resumo"
              className="form-control"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
            ></textarea>
          </div>
          <div className="form-group">
            <label htmlFor="autores">Autores</label>
            <textarea
              id="autores"
              className="form-control"
              value={autores}
              onChange={(e) => setAutores(e.target.value)}
            ></textarea>
          </div>
          <div className="form-group mb-2">
            <label htmlFor="editora">Editora</label>
            <select
              id="editora"
              className="form-control"
              value={codEditora}
              onChange={tratarCombo}
            >
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <button type="submit" className="btn btn-primary">
              Salvar Dados
            </button>
          </div>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;
