// clientes/livros-react/src/LivroDados.js
import { useState } from 'react';
import { ControleEditora } from './controle/ControleEditora';
import { ControleLivros } from './controle/ControleLivros';
import { useNavigate } from 'react-router-dom';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

export default function LivroDados() {

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  function tratarCombo(event) {
    const value = Number(event.target.value);
    setCodEditora(value);
  }

  function incluir(event) {
    event.preventDefault();

    const livro = {
      codigo: "",
      titulo: titulo,
      resumo: resumo,
      autores: autores.split("\n"),
      codEditora: codEditora,
    };

    controleLivro.incluir(livro).then(res => {
      navigate("/");
    });

  }

  return (
    <main className="container">
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="form-group">
          <label htmlFor="titulo">Título:</label>
          <input
            type="text"
            id="titulo"
            className="form-control"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
          />
        </div>
        <div className="form-group">
          <label htmlFor="resumo">Resumo:</label>
          <textarea
            id="resumo"
            className="form-control"
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
          ></textarea>
        </div>
        <div className="form-group">
          <label htmlFor="autores">Autores:</label>
          <textarea
            id="autores"
            className="form-control"
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
          ></textarea>
        </div>
        <div className="form-group">
          <label htmlFor="codEditora">Editora:</label>
          <select
            id="codEditora"
            className="form-control"
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <button type="submit" className="btn btn-primary">
          Salvad Dados
        </button>
      </form>
    </main>
  );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();

  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);

    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  };
}

<main class="container">
  <h2>Dados do Livro</h2>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        name="titulo"
        class="form-control"
        required
        [(ngModel)]="livro.titulo"
      />
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        name="resumo"
        class="form-control"
        [(ngModel)]="livro.resumo"
      ></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select
        name="editora"
        class="form-control"
        required
        [(ngModel)]="livro.codEditora"
      >
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea
        name="autores"
        class="form-control"
        [(ngModel)]="autoresForm"
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>
